# 打包依赖阶段使用golang作为基础镜像
FROM golang:latest as builder

USER root

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags musl -ldflags="-w -s" main.go

# 运行阶段指定alpine作为基础镜像
FROM alpine

LABEL maintainer="chaoxin.lu"

WORKDIR /app

# 将上一个阶段app文件夹下的所有文件复制进来
COPY --from=builder /app/main .
COPY templates/* /app/templates/
COPY static/* /app/static/

# 指定运行时环境变量
ENV GIN_MODE=release \
    SERVER_PORT=6666

ENTRYPOINT ["./main"]
